# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/unit/writestream_sys_test_expanded_schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n5tests/unit/writestream_sys_test_expanded_schema.proto"\x8a\x01\n#WriteStreamSystemTestExpandedSchema\x12\x12\n\nstring_col\x18\x01 \x01(\t\x12\x0f\n\x07int_col\x18\x02 \x01(\x03\x12\x11\n\tfloat_col\x18\x03 \x01(\x01\x12\x10\n\x08time_col\x18\x04 \x01(\x03\x12\x19\n\x11\x61nother_float_col\x18\x05 \x01(\x01'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "tests.unit.writestream_sys_test_expanded_schema_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _WRITESTREAMSYSTEMTESTEXPANDEDSCHEMA._serialized_start = 58
    _WRITESTREAMSYSTEMTESTEXPANDEDSCHEMA._serialized_end = 196
# @@protoc_insertion_point(module_scope)
