# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/unit/writestream_sys_test_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*tests/unit/writestream_sys_test_data.proto"e\n\x19WriteStreamSystemTestData\x12\x12\n\nstring_col\x18\x01 \x01(\t\x12\x0f\n\x07int_col\x18\x02 \x01(\x03\x12\x11\n\tfloat_col\x18\x03 \x01(\x01\x12\x10\n\x08time_col\x18\x04 \x01(\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "tests.unit.writestream_sys_test_data_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _WRITESTREAMSYSTEMTESTDATA._serialized_start = 46
    _WRITESTREAMSYSTEMTESTDATA._serialized_end = 147
# @@protoc_insertion_point(module_scope)
